name: Test and analyze

on: [ push ]

jobs:
    pytests:
        strategy:
            matrix:
                python-version: ["3.7", "3.10"]
            fail-fast: false
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v4
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Install dependencies
                run: |
                    python -m pip install -U pip tox
            -   name: pytest
                run: |
                    tox -e py

    Analysis:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Python 3.10
                uses: actions/setup-python@v4
                with:
                    python-version: "3.10"
            -   name: Install dependencies
                run: |
                    python -m pip install -U pip tox
            -   name: typing
                run: |
                    tox -e typing
            -   name: analysis
                continue-on-error: true
                run: |
                    tox -e analysis

